# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

sass:
  style: compressed

# Setup
title:               Time Wasted
tagline:             '"Only those who risk going too far can possibly find out how far one can go."'
description:         '"The observer, when he seems to himself to be observing a stone, is really, if the physics is to be believed, observing the effects of the stone upon himself."<div class="quote-author">Bertrand Russel</div>'
url:                 http://leepope.com
baseurl:             ''
paginate:            5
exclude: ["lib", "config.rb", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# About/contact
author:
  name:              lee pope
  url:               https://twitter.com/leepopern
  email:             leepope@gmail.com

# Custom vars
disqus_shortname:    leepope
